Remove outdated ocamlbuild command from readme
ocamlbuild was replaced by dune in:
8198d300457a85b9b305ac8e8cbb656443c47d2d

The ocamlbuild command no longer
works and results in the error:

`Error: Unbound module "Slanglib"`