Use ppx_deriving_yojson instead of ppx_yojson_conv
ppx_deriving_yojson now seems to be more maintained, and avoids a
compilation error:

File "web/JargonSteps.ml", line 18, characters 6-12:
18 |   id: string;
           ^^^^^^
Error: Unbound value string_of_yojson